# Generated by Django 3.1.3 on 2022-03-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('post', '0006_auto_20220319_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
    ]
